#TARGET_PROVIDES_CAMERA_HAL := true
USE_DEVICE_SPECIFIC_CAMERA := true
TARGET_HAS_LEGACY_CAMERA_HAL1 := true
BOARD_CAMERA_SENSORS := SONY_IMX219 SLSI_S5K5E3YX
TARGET_NEEDS_TEXT_RELOCATIONS := true
TARGET_NEEDS_PLATFORM_TEXT_RELOCATIONS := true
